/**
 * TIME & LOCATION CONFIGURATION
 */
const CLOCK_CONFIG = {
  clock1: {
    timezone: 'Europe/Stockholm',
    label: 'SWEDEN',
    countryCode: 'SE'
  },
  clock2: {
    useLocalTime: true,
    label: 'CURRENT LOCATION'
  }
};

/**
 * LINK CATEGORIES AND BOOKMARKS
 */
const categories = [
  {
    name: "Google",
    links: [
      { name: "YouTube", url: "https://youtube.com", icon: "youtube" },
      { name: "Calendar", url: "https://calendar.google.com", icon: "calendar" },
      { name: "Mail", url: "https://mail.google.com", icon: "mail" },
      { name: "Drive", url: "https://drive.google.com", icon: "hard-drive" }
    ]
  },
  {
    name: "Finance",
    links: [
      { name: "Kivra", url: "https://kivra.com", icon: "credit-card" },
      { name: "Nordea", url: "https://nordea.com", icon: "bank" },
      { name: "SEB", url: "https://seb.se/logga-in", icon: "bank" },
      { name: "Avanza", url: "https://avanza.se", icon: "trending-up" }
    ]
  },
  {
    name: "Fun",
    links: [
      { name: "GitHub", url: "https://github.com", icon: "github" },
      { name: "Reddit", url: "https://reddit.com", icon: "message-circle" },
      { name: "Wallhaven", url: "https://wallhaven.cc", icon: "image" },
      { name: "Fitgirl", url: "https://fitgirl-repacks.site", icon: "download" }
    ]
  },
  {
    name: "AI",
    links: [
      { name: "ChatGPT", url: "https://chat.openai.com", icon: "message-square" },
      { name: "v0", url: "https://v0.dev", icon: "bot" },
      { name: "Google Studio", url: "https://aistudio.google.com/app/prompts/new_chat", icon: "brain-circuit" }
    ]
  },
  {
    name: "Art",
    links: [
      { name: "Cine2nerdle", url: "https://cine2nerdle.com", icon: "film" },
      { name: "Letterboxd", url: "https://letterboxd.com", icon: "clapperboard" },
      { name: "Plex", url: "https://app.plex.tv", icon: "tv" }
    ]
  }
];

/**
 * WEATHER CONFIGURATION
 */
const WEATHER_CONFIG = {
  apiKey: "bd94f199d3a62747c068b5f09da9bfd8",
  defaultLat: 59.3194903,  // Stockholm coordinates (fallback only)
  defaultLon: 18.075060000000007,
  units: "metric",
  cacheTimeMs: 4 * 60 * 60 * 1000, // Cache weather data for 4 hours
  locationCacheKey: "userLocationCache", // Separate cache for location coordinates
  useGeolocation: true  // Set to true to enable geolocation
}

/**
 * INTERACTIVE PILLS DATA
 */
const VOCABULARY_DATA = [
  { word: "Être", translation: "To be" },
  { word: "Avoir", translation: "To have" },
  { word: "Aller", translation: "To go" },
  { word: "Faire", translation: "To do" },
  { word: "Dire", translation: "To say" },
  { word: "Pouvoir", translation: "Can" },
  { word: "Vouloir", translation: "To want" },
  { word: "Savoir", translation: "To know (fact)" },
  { word: "Connaître", translation: "To know (person)" },
  { word: "Devoir", translation: "Must" },
  { word: "Falloir", translation: "To be necessary" },
  { word: "Croire", translation: "To believe" },
  { word: "Voir", translation: "To see" },
  { word: "Prendre", translation: "To take" },
  { word: "Mettre", translation: "To put" },
  { word: "Parler", translation: "To speak" },
  { word: "Aimer", translation: "To like" },
  { word: "Passer", translation: "To pass" },
  { word: "Penser", translation: "To think" },
  { word: "Comprendre", translation: "To understand" },
  { word: "Demander", translation: "To ask" },
  { word: "Donner", translation: "To give" },
  { word: "Venir", translation: "To come" },
  { word: "Devenir", translation: "To become" },
  { word: "Rester", translation: "To stay" },
  { word: "Arriver", translation: "To arrive" },
  { word: "Partir", translation: "To leave" },
  { word: "Sortir", translation: "To go out" },
  { word: "Entendre", translation: "To hear" },
  { word: "Regarder", translation: "To watch" },
  { word: "Appeler", translation: "To call" },
  { word: "Trouver", translation: "To find" },
  { word: "Chercher", translation: "To look for" },
  { word: "Attendre", translation: "To wait" },
  { word: "Essayer", translation: "To try" },
  { word: "Laisser", translation: "To let" },
  { word: "Sembler", translation: "To seem" },
  { word: "Sentir", translation: "To feel" },
  { word: "Recevoir", translation: "To receive" },
  { word: "Répondre", translation: "To answer" },
  { word: "Vivre", translation: "To live" },
  { word: "Manger", translation: "To eat" },
  { word: "Boire", translation: "To drink" },
  { word: "Dormir", translation: "To sleep" },
  { word: "Travailler", translation: "To work" },
  { word: "Acheter", translation: "To buy" },
  { word: "Payer", translation: "To pay" },
  { word: "Aider", translation: "To help" },
  { word: "Commencer", translation: "To start" },
  { word: "Finir", translation: "To finish" },
  { word: "Oublier", translation: "To forget" },
  { word: "Apprendre", translation: "To learn" },
  { word: "Je", translation: "I" },
  { word: "Tu", translation: "You (informal)" },
  { word: "Il", translation: "He" },
  { word: "Elle", translation: "She" },
  { word: "On", translation: "We (informal)" },
  { word: "Nous", translation: "We" },
  { word: "Vous", translation: "You (formal/plural)" },
  { word: "Ils", translation: "They (masc)" },
  { word: "Elles", translation: "They (fem)" },
  { word: "Ce", translation: "This" },
  { word: "Ça", translation: "That" },
  { word: "Tout", translation: "All" },
  { word: "Rien", translation: "Nothing" },
  { word: "Personne", translation: "Nobody" },
  { word: "Quelqu'un", translation: "Someone" },
  { word: "Mon", translation: "My" },
  { word: "Ton", translation: "Your" },
  { word: "Son", translation: "His/Her" },
  { word: "Notre", translation: "Our" },
  { word: "Votre", translation: "Your (formal)" },
  { word: "Leur", translation: "Their" },
  { word: "Oui", translation: "Yes" },
  { word: "Non", translation: "No" },
  { word: "Si", translation: "If" },
  { word: "Et", translation: "And" },
  { word: "Ou", translation: "Or" },
  { word: "Mais", translation: "But" },
  { word: "Donc", translation: "So" },
  { word: "Car", translation: "Because" },
  { word: "Alors", translation: "Then" },
  { word: "Comme", translation: "Like/As" },
  { word: "Comment", translation: "How" },
  { word: "Pourquoi", translation: "Why" },
  { word: "Quand", translation: "When" },
  { word: "Où", translation: "Where" },
  { word: "Qui", translation: "Who" },
  { word: "Quoi", translation: "What" },
  { word: "Que", translation: "That" },
  { word: "Ici", translation: "Here" },
  { word: "Là", translation: "There" },
  { word: "Maintenant", translation: "Now" },
  { word: "Aujourd'hui", translation: "Today" },
  { word: "Demain", translation: "Tomorrow" },
  { word: "Hier", translation: "Yesterday" },
  { word: "Toujours", translation: "Always" },
  { word: "Jamais", translation: "Never" },
  { word: "Souvent", translation: "Often" },
  { word: "Parfois", translation: "Sometimes" },
  { word: "Encore", translation: "Again" },
  { word: "Déjà", translation: "Already" },
  { word: "Bientôt", translation: "Soon" },
  { word: "Tard", translation: "Late" },
  { word: "Tôt", translation: "Early" },
  { word: "Vite", translation: "Fast" },
  { word: "Lentement", translation: "Slowly" },
  { word: "Très", translation: "Very" },
  { word: "Trop", translation: "Too" },
  { word: "Beaucoup", translation: "A lot" },
  { word: "Peu", translation: "Little" },
  { word: "Assez", translation: "Enough" },
  { word: "Bien", translation: "Well" },
  { word: "Mal", translation: "Badly" },
  { word: "Mieux", translation: "Better" },
  { word: "Moins", translation: "Less" },
  { word: "Plus", translation: "More" },
  { word: "Avec", translation: "With" },
  { word: "Sans", translation: "Without" },
  { word: "Pour", translation: "For" },
  { word: "Par", translation: "By" },
  { word: "Sur", translation: "On" },
  { word: "Sous", translation: "Under" },
  { word: "Dans", translation: "In" },
  { word: "Devant", translation: "In front" },
  { word: "Derrière", translation: "Behind" },
  { word: "Entre", translation: "Between" },
  { word: "Chez", translation: "At" },
  { word: "Avant", translation: "Before" },
  { word: "Après", translation: "After" },
  { word: "Pendant", translation: "During" },
  { word: "Depuis", translation: "Since" },
  { word: "Contre", translation: "Against" },
  { word: "Vers", translation: "Towards" },
  { word: "Sauf", translation: "Except" },
  { word: "Bon", translation: "Good" },
  { word: "Mauvais", translation: "Bad" },
  { word: "Grand", translation: "Big" },
  { word: "Petit", translation: "Small" },
  { word: "Nouveau", translation: "New" },
  { word: "Vieux", translation: "Old" },
  { word: "Jeune", translation: "Young" },
  { word: "Beau", translation: "Beautiful" },
  { word: "Joli", "translation": "Pretty" },
  { word: "Chaud", translation: "Hot" },
  { word: "Froid", "translation": "Cold" },
  { word: "Difficile", "translation": "Difficult" },
  { word: "Facile", "translation": "Easy" },
  { word: "Lourd", translation: "Heavy" },
  { word: "Léger", translation: "Light" },
  { word: "Cher", translation: "Expensive" },
  { word: "Vrai", translation: "True" },
  { word: "Faux", translation: "False" },
  { word: "Même", translation: "Same" },
  { word: "Autre", translation: "Other" },
  { word: "Seul", translation: "Alone" },
  { word: "Premier", translation: "First" },
  { word: "Dernier", translation: "Last" },
  { word: "Prochain", translation: "Next" },
  { word: "Possible", translation: "Possible" },
  { word: "Impossible", translation: "Impossible" },
  { word: "Important", translation: "Important" },
  { word: "Bizarre", translation: "Weird" },
  { word: "Drôle", translation: "Funny" },
  { word: "Triste", translation: "Sad" },
  { word: "Heureux", translation: "Happy" },
  { word: "Fatigué", translation: "Tired" },
  { word: "Malade", translation: "Sick" },
  { word: "Prêt", translation: "Ready" },
  { word: "Désolé", translation: "Sorry" },
  { word: "Sale", translation: "Dirty" },
  { word: "Propre", translation: "Clean" },
  { word: "Plein", translation: "Full" },
  { word: "Vide", translation: "Empty" },
  { word: "Chose", translation: "Thing" },
  { word: "Truc", translation: "Stuff" },
  { word: "Temps", translation: "Time" },
  { word: "Fois", translation: "Occurrence" },
  { word: "Moment", translation: "Moment" },
  { word: "Jour", translation: "Day" },
  { word: "Nuit", translation: "Night" },
  { word: "Semaine", translation: "Week" },
  { word: "An", translation: "Year" },
  { word: "Heure", translation: "Hour" },
  { word: "Monde", translation: "World" },
  { word: "Gens", translation: "People" },
  { word: "Homme", translation: "Man" },
  { word: "Femme", translation: "Woman" },
  { word: "Enfant", translation: "Child" },
  { word: "Ami", translation: "Friend" },
  { word: "Famille", translation: "Family" },
  { word: "Vie", translation: "Life" },
  { word: "Nom", translation: "Name" },
  { word: "Travail", translation: "Work" },
  { word: "École", translation: "School" },
  { word: "Maison", translation: "House" },
  { word: "Ville", translation: "City" },
  { word: "Pays", translation: "Country" },
  { word: "Rue", translation: "Street" },
  { word: "Route", translation: "Road" },
  { word: "Voiture", translation: "Car" },
  { word: "Argent", translation: "Money" },
  { word: "Eau", translation: "Water" },
  { word: "Idée", translation: "Idea" },
  { word: "Raison", translation: "Reason" },
  { word: "Façon", translation: "Way" },
  { word: "Problème", translation: "Problem" },
  { word: "Avis", translation: "Opinion" },
  { word: "Question", translation: "Question" },
  { word: "Histoire", translation: "Story" },
  { word: "Mot", translation: "Word" },
  { word: "Genre", translation: "Type/Like" },
  { word: "Grave", translation: "Serious" },
  { word: "Bref", translation: "Anyway" },
  { word: "Sûrement", translation: "Surely" },
  { word: "Partout", translation: "Everywhere" },
  { word: "Voilà", translation: "There" },
  { word: "Du coup", translation: "So / Therefore (Used constantly)" },
  { word: "En fait", translation: "Actually / In fact" },
  { word: "Carrément", translation: "Totally / Definitely" },
  { word: "C'est clair", translation: "For sure / It's clear" },
  { word: "Quand même", translation: "Anyway / Still / Even so" },
  { word: "A priori", translation: "Seemingly / In principle" },
  { word: "T'inquiète", translation: "Don't worry (Short for Ne t'inquiète pas)" },
  { word: "Laisse tomber", translation: "Forget it / Let it go" },
  { word: "Ça marche", translation: "That works / OK" },
  { word: "Ça roule", translation: "All good / Sounds good" },
  { word: "Pas de souci", translation: "No problem / No worries" },
  { word: "C'est mort", translation: "It's over / No way" },
  { word: "C'est parti", translation: "Let's go / Here we go" },
  { word: "Bosser", translation: "To work (Slang)" },
  { word: "Bouffer", translation: "To eat (Slang)" },
  { word: "Kiffer", translation: "To like / To enjoy (Slang)" },
  { word: "Piger", translation: "To get it / To understand (Slang)" },
  { word: "Se casser", translation: "To leave / To split (Slang)" },
  { word: "Se tirer", translation: "To beat it / To leave (Slang)" },
  { word: "Rigoler", translation: "To laugh / To joke" },
  { word: "Halluciner", translation: "To be amazed / Can't believe it" },
  { word: "Assurer", translation: "To handle it / To be great" },
  { word: "Craquer", translation: "To give in / To lose it" },
  { word: "Gérer", translation: "To manage / To have under control" },
  { word: "Pote", translation: "Buddy / Mate" },
  { word: "Gosse", translation: "Kid / Child" },
  { word: "Boulot", translation: "Job / Work" },
  { word: "Thune", translation: "Money (Slang)" },
  { word: "Fric", translation: "Money (Slang)" },
  { word: "Baraque", translation: "House / Shack" },
  { word: "Bagnole", translation: "Car (Slang)" },
  { word: "Fringues", translation: "Clothes (Slang)" },
  { word: "Bouquin", translation: "Book (Informal)" },
  { word: "Toubib", translation: "Doctor (Slang)" },
  { word: "Flic", translation: "Cop (Slang)" },
  { word: "Gueule", translation: "Face / Mouth (Rude)" },
  { word: "Dingue", translation: "Crazy" },
  { word: "Ouf", translation: "Crazy (Verlan of Fou)" },
  { word: "Nul", translation: "Rubbish / Suck" },
  { word: "Chouette", translation: "Great / Cool" },
  { word: "Relou", translation: "Annoying (Verlan of Lourd)" },
  { word: "Chelou", translation: "Weird (Verlan of Louche)" },
  { word: "Vénère", translation: "Angry (Verlan of Énervé)" },
  { word: "Nickel", translation: "Perfect / Spotless" },
  { word: "Dégueu", translation: "Gross (Short for Dégoutant)" },
  { word: "Crevé", translation: "Exhausted / Dead tired" },
  { word: "Naze", translation: "Lame / Rubbish" },
  { word: "Chiant", translation: "Annoying / Boring" },
  { word: "Bordel", translation: "Mess / Damn (Very common)" },
  { word: "Putain", translation: "Damn / F*ck (Universal punctuation)" },
  { word: "Carte", translation: "Menu (The full selection)" },
  { word: "Menu", translation: "Set Menu (Fixed price)" },
  { word: "Formule", translation: "Combo (e.g., Lunch special)" },
  { word: "Ardoise", translation: "Blackboard (Daily specials)" },
  { word: "Entrée", translation: "Starter / Appetizer" },
  { word: "Plat", translation: "Main Course" },
  { word: "Dessert", translation: "Dessert" },
  { word: "Boisson", translation: "Drink" },
  { word: "Addition", translation: "Bill / Check" },
  { word: "Service compris", translation: "Service Included" },
  { word: "Pourboire", translation: "Tip" },
  { word: "Carafe", translation: "Pitcher (usually tap water)" },
  { word: "Pichet", translation: "Jug (usually wine)" },
  { word: "Saignant", translation: "Rare (Cooking steak)" },
  { word: "À point", translation: "Medium-rare (Standard in France)" },
  { word: "Bien cuit", translation: "Well done" },
  { word: "Bleu", translation: "Very rare / Blue" },
  { word: "Cru", translation: "Raw" },
  { word: "Cuit", translation: "Cooked" },
  { word: "Frit", translation: "Fried" },
  { word: "Rôti", translation: "Roasted" },
  { word: "Grillé", translation: "Grilled" },
  { word: "Poêlé", translation: "Pan-fried" },
  { word: "Vapeur", translation: "Steamed" },
  { word: "Fumé", translation: "Smoked" },
  { word: "Pané", translation: "Breaded" },
  { word: "Gratiné", translation: "Gratin (Cheese crust)" },
  { word: "Maison", translation: "House-made" },
  { word: "Du jour", translation: "Of the day" },
  { word: "Fermier", translation: "Farm-fresh" },
  { word: "Bio", translation: "Organic" },
  { word: "Artisanal", translation: "Artisan / Craft" },
  { word: "Bœuf", translation: "Beef" },
  { word: "Veau", translation: "Veal" },
  { word: "Agneau", translation: "Lamb" },
  { word: "Porc", translation: "Pork" },
  { word: "Volaille", translation: "Poultry" },
  { word: "Poulet", translation: "Chicken" },
  { word: "Canard", translation: "Duck" },
  { word: "Dinde", translation: "Turkey" },
  { word: "Lapin", translation: "Rabbit" },
  { word: "Gibier", translation: "Game meat" },
  { word: "Entrecôte", translation: "Ribeye Steak" },
  { word: "Bavette", translation: "Flank Steak" },
  { word: "Faux-filet", translation: "Sirloin Steak" },
  { word: "Onglet", translation: "Hanger Steak" },
  { word: "Tartare", translation: "Raw minced meat/fish" },
  { word: "Carpaccio", translation: "Thinly sliced raw meat/fish" },
  { word: "Magret", translation: "Duck breast" },
  { word: "Gigot", translation: "Leg of lamb" },
  { word: "Haché", translation: "Minced / Ground" },
  { word: "Saucisse", translation: "Sausage" },
  { word: "Boudin", translation: "Blood/White Sausage" },
  { word: "Andouillette", translation: "Tripe Sausage (Strong taste)" },
  { word: "Jambon", translation: "Ham" },
  { word: "Lardons", translation: "Bacon bits" },
  { word: "Rillettes", translation: "Potted meat spread" },
  { word: "Terrine", translation: "Coarse Pâté" },
  { word: "Foie gras", translation: "Duck/Goose liver" },
  { word: "Poisson", translation: "Fish" },
  { word: "Saumon", translation: "Salmon" },
  { word: "Thon", translation: "Tuna" },
  { word: "Bar", translation: "Sea Bass" },
  { word: "Daurade", translation: "Sea Bream" },
  { word: "Cabillaud", translation: "Cod" },
  { word: "Sole", translation: "Sole" },
  { word: "Moules", translation: "Mussels" },
  { word: "Huîtres", translation: "Oysters" },
  { word: "Crevettes", translation: "Shrimp" },
  { word: "Gambas", translation: "Large Prawns" },
  { word: "Saint-Jacques", translation: "Scallops" },
  { word: "Calamar", translation: "Squid" },
  { word: "Fruits de mer", translation: "Seafood" },
  { word: "Frites", translation: "Fries" },
  { word: "Purée", translation: "Mashed potatoes" },
  { word: "Riz", translation: "Rice" },
  { word: "Pâtes", translation: "Pasta" },
  { word: "Haricots verts", translation: "Green beans" },
  { word: "Légumes", translation: "Vegetables" },
  { word: "Salade", translation: "Salad / Lettuce" },
  { word: "Crudités", translation: "Raw vegetable salad" },
  { word: "Soupe", translation: "Soup" },
  { word: "Velouté", translation: "Creamy soup" },
  { word: "Champignons", translation: "Mushrooms" },
  { word: "Pommes de terre", translation: "Potatoes" },
  { word: "Fromage", translation: "Cheese" },
  { word: "Chèvre", translation: "Goat cheese" },
  { word: "Brebis", translation: "Sheep cheese" },
  { word: "Crème brûlée", translation: "Custard with burnt sugar" },
  { word: "Mousse", translation: "Mousse" },
  { word: "Île flottante", translation: "Floating Island (Dessert)" },
  { word: "Glace", translation: "Ice cream" },
  { word: "Sorbet", translation: "Sorbet" },
  { word: "Noisette", translation: "Espresso with dash of milk" },
  { word: "Vin", translation: "Wine" },
  { word: "Rouge", translation: "Red" },
  { word: "Blanc", translation: "White" },
  { word: "Rosé", translation: "Rose" },
  { word: "Sec", translation: "Dry" },
  { word: "Demi-sec", translation: "Semi-sweet" },
  { word: "Brut", translation: "Dry (Champagne)" },
  { word: "Moelleux", translation: "Sweet wine" },
  { word: "Pression", translation: "Draft beer" },
  { word: "Demi", translation: "Half-pint (25cl)" },
  { word: "Panaché", translation: "Beer with lemonade" },
  { word: "Digestif", translation: "After-dinner liqueur" },
  { word: "Apéritif", translation: "Pre-dinner drink" }
];

const GEOGRAPHY_DATA = [
  { country: "Afghanistan", capital: "Kabul", code: "AF" },
  { country: "Albania", capital: "Tirana", code: "AL" },
  { country: "Algeria", capital: "Algiers", code: "DZ" },
  { country: "Andorra", capital: "Andorra la Vella", code: "AD" },
  { country: "Angola", capital: "Luanda", code: "AO" },
  { country: "Antigua and Barbuda", capital: "Saint John's", code: "AG" },
  { country: "Argentina", capital: "Buenos Aires", code: "AR" },
  { country: "Armenia", capital: "Yerevan", code: "AM" },
  { country: "Australia", capital: "Canberra", code: "AU" },
  { country: "Austria", capital: "Vienna", code: "AT" },
  { country: "Azerbaijan", capital: "Baku", code: "AZ" },
  { country: "Bahamas", capital: "Nassau", code: "BS" },
  { country: "Bahrain", capital: "Manama", code: "BH" },
  { country: "Bangladesh", capital: "Dhaka", code: "BD" },
  { country: "Barbados", capital: "Bridgetown", code: "BB" },
  { country: "Belarus", capital: "Minsk", code: "BY" },
  { country: "Belgium", capital: "Brussels", code: "BE" },
  { country: "Belize", capital: "Belmopan", code: "BZ" },
  { country: "Benin", capital: "Porto-Novo", code: "BJ" },
  { country: "Bhutan", capital: "Thimphu", code: "BT" },
  { country: "Bolivia", capital: "Sucre", code: "BO" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", code: "BA" },
  { country: "Botswana", capital: "Gaborone", code: "BW" },
  { country: "Brazil", capital: "Brasília", code: "BR" },
  { country: "Brunei", capital: "Bandar Seri Begawan", code: "BN" },
  { country: "Bulgaria", capital: "Sofia", code: "BG" },
  { country: "Burkina Faso", capital: "Ouagadougou", code: "BF" },
  { country: "Burundi", capital: "Gitega", code: "BI" },
  { country: "Cabo Verde", capital: "Praia", code: "CV" },
  { country: "Cambodia", capital: "Phnom Penh", code: "KH" },
  { country: "Cameroon", capital: "Yaoundé", code: "CM" },
  { country: "Canada", capital: "Ottawa", code: "CA" },
  { country: "Central African Republic", capital: "Bangui", code: "CF" },
  { country: "Chad", capital: "N'Djamena", code: "TD" },
  { country: "Chile", capital: "Santiago", code: "CL" },
  { country: "China", capital: "Beijing", code: "CN" },
  { country: "Colombia", capital: "Bogotá", code: "CO" },
  { country: "Comoros", capital: "Moroni", code: "KM" },
  { country: "Democratic Republic Congo", capital: "Kinshasa", code: "CD" },
  { country: "Republic of Congo", capital: "Brazzaville", code: "CG" },
  { country: "Costa Rica", capital: "San José", code: "CR" },
  { country: "Croatia", capital: "Zagreb", code: "HR" },
  { country: "Cuba", capital: "Havana", code: "CU" },
  { country: "Cyprus", capital: "Nicosia", code: "CY" },
  { country: "Czech Republic", capital: "Prague", code: "CZ" },
  { country: "Denmark", capital: "Copenhagen", code: "DK" },
  { country: "Djibouti", capital: "Djibouti", code: "DJ" },
  { country: "Dominica", capital: "Roseau", code: "DM" },
  { country: "Dominican Republic", capital: "Santo Domingo", code: "DO" },
  { country: "East Timor", capital: "Dili", code: "TL" },
  { country: "Ecuador", capital: "Quito", code: "EC" },
  { country: "Egypt", capital: "Cairo", code: "EG" },
  { country: "El Salvador", capital: "San Salvador", code: "SV" },
  { country: "Equatorial Guinea", capital: "Malabo", code: "GQ" },
  { country: "Eritrea", capital: "Asmara", code: "ER" },
  { country: "Estonia", capital: "Tallinn", code: "EE" },
  { country: "Eswatini", capital: "Mbabane", code: "SZ" },
  { country: "Ethiopia", capital: "Addis Ababa", code: "ET" },
  { country: "Fiji", capital: "Suva", code: "FJ" },
  { country: "Finland", capital: "Helsinki", code: "FI" },
  { country: "France", capital: "Paris", code: "FR" },
  { country: "Gabon", capital: "Libreville", code: "GA" },
  { country: "Gambia", capital: "Banjul", code: "GM" },
  { country: "Georgia", capital: "Tbilisi", code: "GE" },
  { country: "Germany", capital: "Berlin", code: "DE" },
  { country: "Ghana", capital: "Accra", code: "GH" },
  { country: "Greece", capital: "Athens", code: "GR" },
  { country: "Grenada", capital: "St. George's", code: "GD" },
  { country: "Guatemala", capital: "Guatemala City", code: "GT" },
  { country: "Guinea", capital: "Conakry", code: "GN" },
  { country: "Guinea-Bissau", capital: "Bissau", code: "GW" },
  { country: "Guyana", capital: "Georgetown", code: "GY" },
  { country: "Haiti", capital: "Port-au-Prince", code: "HT" },
  { country: "Honduras", capital: "Tegucigalpa", code: "HN" },
  { country: "Hong Kong", capital: "Hong Kong", code: "HK" },
  { country: "Hungary", capital: "Budapest", code: "HU" },
  { country: "Iceland", capital: "Reykjavik", code: "IS" },
  { country: "India", capital: "New Delhi", code: "IN" },
  { country: "Indonesia", capital: "Jakarta", code: "ID" },
  { country: "Iran", capital: "Tehran", code: "IR" },
  { country: "Iraq", capital: "Baghdad", code: "IQ" },
  { country: "Ireland", capital: "Dublin", code: "IE" },
  { country: "Israel", capital: "Jerusalem", code: "IL" },
  { country: "Italy", capital: "Rome", code: "IT" },
  { country: "Ivory Coast", capital: "Yamoussoukro", code: "CI" },
  { country: "Jamaica", capital: "Kingston", code: "JM" },
  { country: "Japan", capital: "Tokyo", code: "JP" },
  { country: "Jordan", capital: "Amman", code: "JO" },
  { country: "Kazakhstan", capital: "Astana", code: "KZ" },
  { country: "Kenya", capital: "Nairobi", code: "KE" },
  { country: "Kiribati", capital: "South Tarawa", code: "KI" },
  { country: "Kosovo", capital: "Pristina", code: "XK" },
  { country: "Kuwait", capital: "Kuwait City", code: "KW" },
  { country: "Kyrgyzstan", capital: "Bishkek", code: "KG" },
  { country: "Laos", capital: "Vientiane", code: "LA" },
  { country: "Latvia", capital: "Riga", code: "LV" },
  { country: "Lebanon", capital: "Beirut", code: "LB" },
  { country: "Lesotho", capital: "Maseru", code: "LS" },
  { country: "Liberia", capital: "Monrovia", code: "LR" },
  { country: "Libya", capital: "Tripoli", code: "LY" },
  { country: "Liechtenstein", capital: "Vaduz", code: "LI" },
  { country: "Lithuania", capital: "Vilnius", code: "LT" },
  { country: "Luxembourg", capital: "Luxembourg", code: "LU" },
  { country: "Macau", capital: "Macau", code: "MO" },
  { country: "Madagascar", capital: "Antananarivo", code: "MG" },
  { country: "Malawi", capital: "Lilongwe", code: "MW" },
  { country: "Malaysia", capital: "Kuala Lumpur", code: "MY" },
  { country: "Maldives", capital: "Malé", code: "MV" },
  { country: "Mali", capital: "Bamako", code: "ML" },
  { country: "Malta", capital: "Valletta", code: "MT" },
  { country: "Marshall Islands", capital: "Majuro", code: "MH" },
  { country: "Mauritania", capital: "Nouakchott", code: "MR" },
  { country: "Mauritius", capital: "Port Louis", code: "MU" },
  { country: "Mexico", capital: "Mexico City", code: "MX" },
  { country: "Micronesia", capital: "Palikir", code: "FM" },
  { country: "Moldova", capital: "Chisinau", code: "MD" },
  { country: "Monaco", capital: "Monaco", code: "MC" },
  { country: "Mongolia", capital: "Ulaanbaatar", code: "MN" },
  { country: "Montenegro", capital: "Podgorica", code: "ME" },
  { country: "Morocco", capital: "Rabat", code: "MA" },
  { country: "Mozambique", capital: "Maputo", code: "MZ" },
  { country: "Myanmar", capital: "Naypyidaw", code: "MM" },
  { country: "Namibia", capital: "Windhoek", code: "NA" },
  { country: "Nauru", capital: "Yaren", code: "NR" },
  { country: "Nepal", capital: "Kathmandu", code: "NP" },
  { country: "Netherlands", capital: "Amsterdam", code: "NL" },
  { country: "New Zealand", capital: "Wellington", code: "NZ" },
  { country: "Nicaragua", capital: "Managua", code: "NI" },
  { country: "Niger", capital: "Niamey", code: "NE" },
  { country: "Nigeria", capital: "Abuja", code: "NG" },
  { country: "North Korea", capital: "Pyongyang", code: "KP" },
  { country: "North Macedonia", capital: "Skopje", code: "MK" },
  { country: "Norway", capital: "Oslo", code: "NO" },
  { country: "Oman", capital: "Muscat", code: "OM" },
  { country: "Pakistan", capital: "Islamabad", code: "PK" },
  { country: "Palau", capital: "Ngerulmud", code: "PW" },
  { country: "Palestine", capital: "Ramallah", code: "PS" },
  { country: "Panama", capital: "Panama City", code: "PA" },
  { country: "Papua New Guinea", capital: "Port Moresby", code: "PG" },
  { country: "Paraguay", capital: "Asunción", code: "PY" },
  { country: "Peru", capital: "Lima", code: "PE" },
  { country: "Philippines", capital: "Manila", code: "PH" },
  { country: "Poland", capital: "Warsaw", code: "PL" },
  { country: "Portugal", capital: "Lisbon", code: "PT" },
  { country: "Qatar", capital: "Doha", code: "QA" },
  { country: "Romania", capital: "Bucharest", code: "RO" },
  { country: "Russia", capital: "Moscow", code: "RU" },
  { country: "Rwanda", capital: "Kigali", code: "RW" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", code: "KN" },
  { country: "Saint Lucia", capital: "Castries", code: "LC" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", code: "VC" },
  { country: "Samoa", capital: "Apia", code: "WS" },
  { country: "San Marino", capital: "San Marino", code: "SM" },
  { country: "Sao Tome and Principe", capital: "São Tomé", code: "ST" },
  { country: "Saudi Arabia", capital: "Riyadh", code: "SA" },
  { country: "Senegal", capital: "Dakar", code: "SN" },
  { country: "Serbia", capital: "Belgrade", code: "RS" },
  { country: "Seychelles", capital: "Victoria", code: "SC" },
  { country: "Sierra Leone", capital: "Freetown", code: "SL" },
  { country: "Singapore", capital: "Singapore", code: "SG" },
  { country: "Slovakia", capital: "Bratislava", code: "SK" },
  { country: "Slovenia", capital: "Ljubljana", code: "SI" },
  { country: "Solomon Islands", capital: "Honiara", code: "SB" },
  { country: "Somalia", capital: "Mogadishu", code: "SO" },
  { country: "South Africa", capital: "Pretoria", code: "ZA" },
  { country: "South Korea", capital: "Seoul", code: "KR" },
  { country: "South Sudan", capital: "Juba", code: "SS" },
  { country: "Spain", capital: "Madrid", code: "ES" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", code: "LK" },
  { country: "Sudan", capital: "Khartoum", code: "SD" },
  { country: "Suriname", capital: "Paramaribo", code: "SR" },
  { country: "Sweden", capital: "Stockholm", code: "SE" },
  { country: "Switzerland", capital: "Bern", code: "CH" },
  { country: "Syria", capital: "Damascus", code: "SY" },
  { country: "Taiwan", capital: "Taipei", code: "TW" },
  { country: "Tajikistan", capital: "Dushanbe", code: "TJ" },
  { country: "Tanzania", capital: "Dodoma", code: "TZ" },
  { country: "Thailand", capital: "Bangkok", code: "TH" },
  { country: "Togo", capital: "Lomé", code: "TG" },
  { country: "Tonga", capital: "Nuku'alofa", code: "TO" },
  { country: "Trinidad and Tobago", capital: "Port of Spain", code: "TT" },
  { country: "Tunisia", capital: "Tunis", code: "TN" },
  { country: "Turkey", capital: "Ankara", code: "TR" },
  { country: "Turkmenistan", capital: "Ashgabat", code: "TM" },
  { country: "Tuvalu", capital: "Funafuti", code: "TV" },
  { country: "Uganda", capital: "Kampala", code: "UG" },
  { country: "Ukraine", capital: "Kyiv", code: "UA" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", code: "AE" },
  { country: "United Kingdom", capital: "London", code: "GB" },
  { country: "United States", capital: "Washington, D.C.", code: "US" },
  { country: "Uruguay", capital: "Montevideo", code: "UY" },
  { country: "Uzbekistan", capital: "Tashkent", code: "UZ" },
  { country: "Vanuatu", capital: "Port Vila", code: "VU" },
  { country: "Vatican City", capital: "Vatican City", code: "VA" },
  { country: "Venezuela", capital: "Caracas", code: "VE" },
  { country: "Vietnam", capital: "Hanoi", code: "VN" },
  { country: "Yemen", capital: "Sanaa", code: "YE" },
  { country: "Zambia", capital: "Lusaka", code: "ZM" },
  { country: "Zimbabwe", capital: "Harare", code: "ZW" }
];

const GENERAL_KNOWLEDGE_QUESTIONS = [
  { question: "The Mesopotamian epic regarding a king's quest for immortality and his friendship with the wild man Enkidu.", answer: "The Epic of Gilgamesh" },
  { question: "Hieronymus Bosch's triptych depicting Eden, a surreal playground of sin, and a nightmarish hellscape.", answer: "The Garden of Earthly Delights" },
  { question: "The 1913 Stravinsky ballet whose primitive rhythms and dissonance caused a riot at its Paris premiere.", answer: "The Rite of Spring" },
  { question: "The philosophical concept of 'non-action' or 'effortless action' central to Daoism.", answer: "Wu Wei" },
  { question: "The 1618 act of throwing Catholic officials from a castle window, sparking the Thirty Years' War.", answer: "The Defenestration of Prague" },
  { question: "Dostoevsky's novel where Raskolnikov murders a pawnbroker to test his theory of the 'extraordinary man'.", answer: "Crime and Punishment" },
  { question: "The ancient trade route network connecting the East and West, named after a lucrative Chinese textile.", answer: "The Silk Road" },
  { question: "Gericault's romantic painting depicting the starving survivors of a shipwreck adrift on a makeshift vessel.", answer: "The Raft of the Medusa" },
  { question: "The Japanese aesthetic of finding beauty in imperfection and transience.", answer: "Wabi-sabi" },
  { question: "The 19th-century conflict fought between Britain and China over the importation of an addictive narcotic.", answer: "The Opium Wars" },
  { question: "Gabriel Garcia Marquez's saga of the Buendía family in Macondo, a masterpiece of magical realism.", answer: "One Hundred Years of Solitude" },
  { question: "The architectural style characterized by flying buttresses, ribbed vaults, and stained glass windows.", answer: "Gothic Architecture" },
  { question: "The 1969 music festival in Bethel, New York, that became the definitive symbol of the counterculture era.", answer: "Woodstock" },
  { question: "Plato's allegory describing prisoners who see only shadows on a wall, mistaking them for reality.", answer: "The Allegory of the Cave" },
  { question: "The massive 1937 mural by Picasso depicting the horrors of the German bombing of a Basque town.", answer: "Guernica" },
  { question: "The 11th-century Japanese work by Lady Murasaki, often cited as the world's first psychological novel.", answer: "The Tale of Genji" },
  { question: "The split in 1054 that divided Christianity into the Roman Catholic and Eastern Orthodox churches.", answer: "The Great Schism" },
  { question: "The artistic movement of Dali and Magritte that sought to release the creative potential of the unconscious mind.", answer: "Surrealism" },
  { question: "The modernist poem by T.S. Eliot beginning, 'April is the cruellest month...'", answer: "The Waste Land" },
  { question: "The Rosetta Stone provided the key to deciphering this ancient writing system.", answer: "Egyptian Hieroglyphs" },
  { question: "The 1868 event that restored imperial rule to Japan and accelerated its industrialization.", answer: "The Meiji Restoration" },
  { question: "The mesmerizing rhythmic pattern used by Ravel in his most famous orchestral piece, which repeats for 15 minutes.", answer: "Bolero" },
  { question: "The mythological titan punished by Zeus to roll a boulder up a hill for eternity.", answer: "Sisyphus" },
  { question: "The 17th-century Dutch painter known for his mastery of light and shadow in 'The Night Watch'.", answer: "Rembrandt" },
  { question: "The dystopian novel by Huxley set in a genetic caste system obsessed with pleasure and the drug 'soma'.", answer: "Brave New World" },
  { question: "The 19th-century theory of 'Manifest Destiny' justified the westward expansion of this nation.", answer: "The United States" },
  { question: "The collection of Middle Eastern folk tales framed by Scheherazade telling stories to save her life.", answer: "One Thousand and One Nights" },
  { question: "The 1453 event where the Ottomans breached the walls of Constantinople, ending the Byzantine Empire.", answer: "The Fall of Constantinople" },
  { question: "The Norwegian expressionist painting depicting a figure with an agonizing open-mouthed expression against a blood-red sky.", answer: "The Scream" },
  { question: "The philosophical razor suggesting the simplest explanation is usually the correct one.", answer: "Occam's Razor" },
  { question: "The 1957 launch of this Soviet satellite marked the beginning of the Space Age.", answer: "Sputnik 1" },
  { question: "Milton's epic poem explicitly stated to 'justify the ways of God to men', retelling the Fall of Man.", answer: "Paradise Lost" },
  { question: "The ancient library in Egypt, intended to be a repository of all human knowledge, tragically destroyed.", answer: "The Library of Alexandria" },
  { question: "The distinct style of singing developed by African American slaves to express religious devotion and sorrow.", answer: "Spirituals" },
  { question: "The 1815 battle that marked the final defeat of Napoleon Bonaparte.", answer: "Waterloo" },
  { question: "The literary technique where a character's thoughts are presented as a continuous, unedited flow.", answer: "Stream of Consciousness" },
  { question: "The prehistoric monument in England consisting of a ring of standing stones, aligned with the solstice.", answer: "Stonehenge" },
  { question: "The political philosophy of Machiavelli arguing that the ends justify the means for a ruler.", answer: "Machiavellianism" },
  { question: "The 19th-century art movement focused on capturing the momentary effect of light, led by Monet and Renoir.", answer: "Impressionism" },
  { question: "The epic Sanskrit scripture that is a conversation between Prince Arjuna and the god Krishna.", answer: "The Bhagavad Gita" },
  { question: "The Frank Lloyd Wright house built over a waterfall in Pennsylvania, an icon of organic architecture.", answer: "Fallingwater" },
  { question: "The massive limestone statue in Egypt with the body of a lion and the head of a human.", answer: "The Great Sphinx" },
  { question: "The 1919 German art school that combined crafts and fine arts, famous for its functionalist design.", answer: "Bauhaus" },
  { question: "The mythological river in the Greek underworld from which souls drink to forget their past lives.", answer: "The River Lethe" },
  { question: "The 1215 document forced upon King John of England, establishing that the king is not above the law.", answer: "Magna Carta" },
  { question: "The complex calendar system of this Mesoamerican civilization that tracked 'Long Count' cycles.", answer: "The Maya" },
  { question: "Goethe's tragic play about a scholar who makes a pact with the devil Mephistopheles.", answer: "Faust" },
  { question: "The 18th-century intellectual movement emphasizing reason, science, and individualism over tradition.", answer: "The Enlightenment" },
  { question: "The collection of speeches and teachings of Confucius and his disciples.", answer: "The Analects" },
  { question: "The 1959 jazz album by Miles Davis that pioneered modal jazz and is the best-selling jazz album of all time.", answer: "Kind of Blue" },
  { question: "The ancient city carved into pink sandstone cliffs in Jordan, once the capital of the Nabataeans.", answer: "Petra" },
  { question: "The 19th-century Russian author of 'War and Peace' and 'Anna Karenina'.", answer: "Leo Tolstoy" },
  { question: "The political barrier that divided Berlin from 1961 to 1989, symbolizing the Cold War.", answer: "The Berlin Wall" },
  { question: "The artistic technique of using strong contrasts between light and dark, perfected by Caravaggio.", answer: "Chiaroscuro" },
  { question: "The 1347 pandemic caused by Yersinia pestis that wiped out a third of Europe's population.", answer: "The Black Death" },
  { question: "The absurdist play by Samuel Beckett where two characters wait endlessly for someone who never arrives.", answer: "Waiting for Godot" },
  { question: "The 16th-century astronomer who formulated the model that the Earth revolves around the Sun.", answer: "Nicolaus Copernicus" },
  { question: "The grand mausoleum in Agra, India, built by Shah Jahan in memory of his favorite wife.", answer: "The Taj Mahal" },
  { question: "The 'Lost Generation' writer who chronicled the Jazz Age in 'The Great Gatsby'.", answer: "F. Scott Fitzgerald" },
  { question: "The ancient Greek war between Athens and Sparta that reshaped the ancient world.", answer: "The Peloponnesian War" },
  { question: "The 20th-century Mexican painter known for her uncompromising self-portraits and use of vibrant colors.", answer: "Frida Kahlo" },
  { question: "The philosophical concept of the 'Superman' (Übermensch) introduced by Friedrich Nietzsche.", answer: "Übermensch" },
  { question: "The 1789 event where French revolutionaries stormed a prison fortress, igniting the Revolution.", answer: "The Storming of the Bastille" },
  { question: "The epic poem by Homer recounting the final year of the Trojan War.", answer: "The Iliad" },
  { question: "The haunting 1939 song by Billie Holiday protesting the lynching of Black Americans.", answer: "Strange Fruit" },
  { question: "The colossal terracotta army buried with the first Emperor of China to protect him in the afterlife.", answer: "The Terracotta Army" },
  { question: "The 19th-century existentialist philosopher who wrote 'Fear and Trembling' and 'Either/Or'.", answer: "Søren Kierkegaard" },
  { question: "The complex, nonlinear narrative style of James Joyce's 1922 novel set in a single day in Dublin.", answer: "Ulysses" },
  { question: "The 1930 painting by Grant Wood depicting a farmer and his daughter standing before a gothic-style house.", answer: "American Gothic" },
  { question: "The series of holy wars initiated by the Latin Church in the medieval period to recover the Holy Land.", answer: "The Crusades" },
  { question: "The metaphysical poet who wrote 'No man is an island' and 'Death, be not proud'.", answer: "John Donne" },
  { question: "The 1648 peace treaties that ended the Thirty Years' War and established the concept of state sovereignty.", answer: "The Peace of Westphalia" },
  { question: "The 4'33\" composition by John Cage consisting entirely of silence (ambient noise).", answer: "4'33\"" },
  { question: "The founder of the Mongol Empire who established the largest contiguous land empire in history.", answer: "Genghis Khan" },
  { question: "The 19th-century literary movement emphasizing emotion, nature, and the sublime.", answer: "Romanticism" },
  { question: "The ancient code of law from Babylon famous for the principle of 'an eye for an eye'.", answer: "The Code of Hammurabi" },
  { question: "The unfinished basilica in Barcelona designed by Antoni Gaudí, under construction since 1882.", answer: "La Sagrada Família" },
  { question: "The tragic heroine of Flaubert's novel who seeks to escape provincial life through affairs and spending.", answer: "Madame Bovary" },
  { question: "The 1917 political upheaval in Russia that dismantled the Tsarist autocracy and led to the Soviet Union.", answer: "The Russian Revolution" },
  { question: "The Renaissance polymath who kept mirrored notebooks and painted the 'Mona Lisa'.", answer: "Leonardo da Vinci" },
  { question: "The ancient Hindu text dealing with the art of living, love, and sexual behavior.", answer: "The Kama Sutra" },
  { question: "The feminist essay by Virginia Woolf arguing a woman needs money and her own space to write fiction.", answer: "A Room of One's Own" },
  { question: "The 1517 document by Martin Luther that criticized the Catholic Church and sparked the Reformation.", answer: "The 95 Theses" },
  { question: "The massive temple complex in Cambodia, originally built as a Hindu temple for the Khmer Empire.", answer: "Angkor Wat" },
  { question: "The philosophical school founded by Zeno, teaching self-control and fortitude as a means to overcome emotions.", answer: "Stoicism" },
  { question: "The classic Chinese novel about a monk's journey to India, accompanied by the Monkey King.", answer: "Journey to the West" },
  { question: "The 1818 novel by Mary Shelley often considered the first true science fiction story.", answer: "Frankenstein" },
  { question: "The American poet known for his free verse and the collection 'Leaves of Grass'.", answer: "Walt Whitman" },
  { question: "The 19th-century battle charge in the Crimean War immortalized by Tennyson's poem.", answer: "The Charge of the Light Brigade" },
  { question: "The Dadaist artwork by Duchamp consisting of a porcelain urinal signed 'R. Mutt'.", answer: "Fountain" },
  { question: "The allegorical novella by Orwell where farm animals stage a revolution that devolves into tyranny.", answer: "Animal Farm" },
  { question: "The medieval conqueror and founder of the Mali Empire, often regarded as the richest man in history.", answer: "Mansa Musa" },
  { question: "The distinct period of Japanese history characterized by isolationist foreign policy (1603-1867).", answer: "The Edo Period" },
  { question: "The influential 19th-century play by Ibsen about a woman leaving her stifling marriage and family.", answer: "A Doll's House" },
  { question: "The 20th-century architectural style characterized by raw concrete and blocky, fortress-like structures.", answer: "Brutalism" },
  { question: "The Greek tragedy by Sophocles where the protagonist unwittingly kills his father and marries his mother.", answer: "Oedipus Rex" },
  { question: "The 1905 scientific papers by Einstein that introduced the theory of special relativity.", answer: "Annus Mirabilis Papers" },
  { question: "The Spanish Golden Age painter of 'Las Meninas', depicting the royal court and the act of painting itself.", answer: "Diego Velázquez" },
  { question: "The 17th-century English philosopher who described life in the state of nature as 'nasty, brutish, and short'.", answer: "Thomas Hobbes" },
  { question: "The epic French novel by Hugo tracing the life of ex-convict Jean Valjean.", answer: "Les Misérables" }
];

/**
 * ICON MAPPINGS - Simple SVG icons based on Lucide icons
 */
const icons = {
  // Used icons only
  "hard-drive": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="12" x2="2" y2="12"></line><path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"></path><line x1="6" y1="16" x2="6.01" y2="16"></line><line x1="10" y1="16" x2="10.01" y2="16"></line></svg>`,
  calendar: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>`,
  mail: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>`,
  github: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>`,
  "credit-card": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect><line x1="1" y1="10" x2="23" y2="10"></line></svg>`,
  bank: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>`,
  "trending-up": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline><polyline points="17 6 23 6 23 12"></polyline></svg>`,
  youtube: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg>`,
  film: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg>`,
  "message-circle": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>`,
  "message-square": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>`,
  image: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>`,
  download: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>`,
  bot: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="10" rx="2"></rect><circle cx="12" cy="5" r="2"></circle><path d="M12 7v4"></path><line x1="8" y1="16" x2="8" y2="16"></line><line x1="16" y1="16" x2="16" y2="16"></line></svg>`,
  "brain-circuit": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 4.5a2.5 2.5 0 0 0-4.96-.46 2.5 2.5 0 0 0-1.98 3 2.5 2.5 0 0 0-1.32 4.24 3 3 0 0 0 .34 5.58 2.5 2.5 0 0 0 2.96 3.08 2.5 2.5 0 0 0 4.91.05L12 20V4.5Z"></path><path d="M16 8V5c0-1.1.9-2 2-2"></path><path d="M12 13h4"></path><path d="M12 18h6a2 2 0 0 1 2 2v1"></path><path d="M12 8h8"></path><path d="M20.5 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"></path><path d="M16.5 13a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"></path><path d="M20.5 21a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"></path><path d="M18.5 3a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"></path></svg>`,
  clapperboard: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 11v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8H4Z"></path><path d="m4 11-.88-2.87a2 2 0 0 1 1.33-2.5l11.48-3.5a2 2 0 0 1 2.5 1.33l.87 2.87L4 11.01Z"></path><path d="m6.6 4.99 3.38 4.2"></path><path d="m11.86 3.38 3.38 4.2"></path></svg>`,
  tv: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="15" rx="2" ry="2"></rect><polyline points="17 2 12 7 7 2"></polyline></svg>`,
  search: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>`,
  // Weather Icons
  "cloud": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"></path></svg>`,
  "cloud-rain": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"></path><path d="M16 14v6"></path><path d="M8 14v6"></path><path d="M12 16v6"></path></svg>`,
  "cloud-snow": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"></path><path d="M8 15h.01"></path><path d="M8 19h.01"></path><path d="M12 17h.01"></path><path d="M12 21h.01"></path><path d="M16 15h.01"></path><path d="M16 19h.01"></path></svg>`,
  "cloud-lightning": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 .5 8.973"></path><path d="m13 12-3 5h4l-3 5"></path></svg>`,
  "cloud-drizzle": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"></path><path d="M8 19v1"></path><path d="M8 14v1"></path><path d="M16 19v1"></path><path d="M16 14v1"></path><path d="M12 21v1"></path><path d="M12 16v1"></path></svg>`,
  "sun": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2"></path><path d="M12 20v2"></path><path d="m4.93 4.93 1.41 1.41"></path><path d="m17.66 17.66 1.41 1.41"></path><path d="M2 12h2"></path><path d="M20 12h2"></path><path d="m6.34 17.66-1.41 1.41"></path><path d="m19.07 4.93-1.41 1.41"></path></svg>`,
  "moon": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path></svg>`,
  "cloud-fog": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"></path><path d="M16 17H7"></path><path d="M17 21H9"></path></svg>`,
  "thermometer": `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z"></path></svg>`,
  "map": `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"></path><circle cx="12" cy="10" r="3"></circle></svg>`,
  // Fallback icon
  bookmark: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg>`
}

/**
 * SEARCH COMMANDS
 */
const SEARCH_COMMANDS = {
  'y': { url: 'https://www.youtube.com/results?search_query=', label: 'YouTube', icon: 'youtube' },
  'r': { url: 'https://www.reddit.com/search/?q=', label: 'Reddit', icon: 'bot' },
  'm': { url: 'https://www.google.com/maps/search/', label: 'Maps', icon: 'map' }
};

/**
 * STOCK CONFIGURATION
 */
const STOCK_CONFIG = {
  symbol: 'GRANGX.ST', // .ST suffix for First North Stockholm
  apiKey: '', // Not needed for CORS proxy method
  cacheTimeMs: 15 * 60 * 1000
};

/**
 * WEATHER ICON MAPPING - OpenWeatherMap codes to SVG icons
 */
const weatherIconMap = {
  '01d': 'sun',
  '01n': 'moon',
  '02d': 'cloud',
  '02n': 'cloud',
  '03d': 'cloud',
  '03n': 'cloud',
  '04d': 'cloud',
  '04n': 'cloud',
  '09d': 'cloud-drizzle',
  '09n': 'cloud-drizzle',
  '10d': 'cloud-rain',
  '10n': 'cloud-rain',
  '11d': 'cloud-lightning',
  '11n': 'cloud-lightning',
  '13d': 'cloud-snow',
  '13n': 'cloud-snow',
  '50d': 'cloud-fog',
  '50n': 'cloud-fog',
};
