export const CARD_BONUSES = {
    TRIPPLE_A_BONUS: 800,
    SIZE_MATTERS_BONUS: 800,
    ABSTINENCE_INCREMENT: 50,
    GOONER_STREAK_MULTIPLIER: 150,
    DOPPEL_BONUS: 300,
    SLEEPER_BONUS: 1.8,
    SPREE_INCREMENT: 10,
    AEGIS_PER_LETTER: 20,
    AEGIS_MAX: 2000,
    VAMPIRIC_PERCENT: 0.10,
    BEAR_THRESHOLD: 40,
    BEAR_PER_COIN: 10,
    BULL_THRESHOLD: 5,
    BULL_MULTIPLIER: 1.8,
    SCAVENGER_PER_TWO: 1,
    MAKESHIFT_BONUS: 1.8,
    ENTROPY_VALUE_BONUS: 2,
    HANDS_OFF_PENALTY: 0.8,
    HANDS_OFF_BONUS: 1.2,
    PILGRIM_PER_LETTER: 200,
    FIERCE_WARRIOR_BASE: 100,
    FIERCE_WARRIOR_COMBO: 200,
    WISE_WARRIOR_BASE: 1.2,
    WISE_WARRIOR_COMBO: 1.4,
    LAST_STAND: 3,
    PACKLEADER_ACTIVE: true,
    MERCANTILE_BONUS: 1,
};

export const WORD_LISTS = {
    NUMBER_WORDS: {
        'ONE': 1.1, 'TWO': 1.2, 'THREE': 1.3, 'FOUR': 1.4,
        'FIVE': 1.5, 'SIX': 1.6, 'SEVEN': 1.7, 'EIGHT': 1.8, 'NINE': 1.9
    },
};
